name: Compile cross-ng 1.26
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Clone kernel source
      run: git clone https://github.com/crosstool-ng/crosstool-ng

    - name: Set up build environment
      run: |	  
          cp install_build_package.sh ./crosstool-ng/
            cd crosstool-ng/
          chmod +x install_build_package.sh
          ./install_build_package.sh
          ./bootstrap
          ./configure
          make
          sudo make install
          ct-ng -v >CompileResult.log
          history >command.log 
          
    - name: SSH connection to Actions
      uses: P3TERX/ssh2actions@v1.0.0
      if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
      env:
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}

      # 创建 GitHub Release 并上传文件
    - name: Upload firmware to release
      uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: path/**/[abc]rtifac?/*
        
      # 删除旧的工作流运行记录（可选）
    - name: Delete workflow runs
      uses: bigtan/delete-workflow-runs@main
      with:
          retain_days: 1
          keep_minimum_runs: 3

      # 删除旧的发布（可选）
    - name: Remove old Releases
      uses: dev-drprasad/delete-older-releases@v0.2.1
      if: env.UPLOAD_RELEASE == 'true' && !cancelled()
      with:
          keep_latest: 3
          delete_tags: true
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
